name: GitHub Repo Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  run-stats:
    runs-on: ubuntu-latest
    steps:
      - name: run-stats
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ github.repository }}
          ghtoken: ${{ secrets.REPOSTATS_TOKEN }}
          databranch: github-repo-stats
          ghpagesprefix: '.'
